### ISSUE TITLE
Up To 15 Ether Bug Hunt For Upcoming Angel Token ICO

### ISSUE THREAD

**Issue by bitcoinfriends** [JGcarv/ethereum-bounty-hunters#17]
Please join our Solidity bug hunt over on Reddit here:

https://www.reddit.com/r/ethdev/comments/7e2h30/up_to_15_ether_bug_hunt_for_upcoming_angel_token/

We need some great solidity developers to review our smart contract and to try to find any bugs for our upcoming ICO on November 27th.

1) You can find a simple writeup/overview of the main intended behaviour of the smart contract functionality and things to check for here:

https://docs.google.com/spreadsheets/d/1XcfoNxQsmHdSNknKSQAH77kE5VZNB3h0h6cOZZ6uQak/edit?usp=sharing

Victor, our developer has also included numerous notes inside the code that explains the functionality and purpose, so I think you will find it relatively easy to understand the code.

You can find the smart contracts and source code on our Github account here: https://github.com/bitcoinfriends/angel-contracts

Feel free to deploy it on Rinkeby or Ropsten to test various functionality.

2) All bugs found will be rewarded.

CRITICAL BUGS WILL BE REWARDED WITH A MINIMUM OF 10 ETHER UP TO A MAXIMUM OF 15 ETHER:

a) If there is the ability to steal investor Ether funds, including being able to modify the receiving Ethereum addresses in the smart contract or something similar that would be a critical bug.

b) If there is the ability for investors to claim more Ether refunds than what they are entitled to according to the intended use that would be a critical bug. This includes the ability to refund more tokens than originally invested from a particular address.

c) If there is the ability by anyone to mint more tokens than intended by the smart contract according to the investments made and the pricing ladder found in the spreadsheet above (sheet 2), or if there is the ability to steal tokens in some way that is a critical bug.

d) 20% of Ether funds invested not being immediately sent to Angel Foundation address: 0x2b0556a6298eA3D35E90F1df32cc126b31F59770 or if there is a possibility to delay and/or divert these funds to be sent somewhere else, or lock them from being sent that is a critical bug.

e) 50% of the Ether funds invested and not refunded during the first 100 days following ICO launch date (Nov 27th) so March 7th 2018 should be sent to Angel Foundation address: 0x2b0556a6298eA3D35E90F1df32cc126b31F59770 after 100 days. If this is not working as intended it is a critical bug.

f) All remaining Ether funds invested that have not been refunded during the first 150 days following ICO launch date (Nov 27th) so April 26th 2018 should be sent to Angel Foundation address: 0x2b0556a6298eA3D35E90F1df32cc126b31F59770 after 150 days have passed. If this is not working as intended it is a critical bug.

MAJOR BUGS WILL BE REWARDED WITH A MINIMUM OF 5 ETHER UP TO A MAXIMUM OF 10 ETHER:

g) If the refunds are not working as intended that is a major bug. Investors should be able to refund all or some of their tokens purchased during the ICO during the first 100 days from the ICO launch date which is November 27th 12:00 GMT, so March 7th 2018, and receive an 80% Ether refund for those tokens returned, and for a further 50 days (following the first 100 days), so April 26th 2018, they should be able to refund some or all of the tokens purchased for a refund of 40% of the original Ether invested.

h) If the minting of tokens does not working as intended, or if tokens are not being immediately being sent to the investor after minting as intended that would be a major bug.

i) If the minting of tokens for the Angel Foundation (3 tokens should be minted for the Angel Foundation address: 0xEb685b132bDCb0Bf5241B1c872a1C7A364dF0cbB for every 7 tokens minted for investors) is not working as intended that is a major bug.

j) If there is a problem with the pricing ladder/calculation so that tokens are not minted and sent to investors at the intended rate that is a major bug.

MINOR BUGS WILL BE REWARDED WITH A MINIMUM OF 0.5 ETHER UP TO A MAXIMUM OF 3 ETHER

k) If there are gas issues meaning that the contract is using more gas than needed or required for the calculations it does.

l) Other bugs or issues that will or could cause problems for us as a team, or for the investors in the ICO.

3. Our developer is very busy on a project at the moment, so mostly you will be dealing with an Angel Foundation team member who is a non-developer in this thread. So please excuse my lack of understanding at times, and please try to explain like you would to a 5-year old! :)

Looking forward to your comments about the code and any issues/problems you may find.

**Comment by loul42** [comment]
FYI, this one is over https://www.reddit.com/r/ethdev/comments/7e2h30/up_to_15_ether_bug_hunt_for_upcoming_angel_token/dqc16v4/

**Comment by JGcarv** [comment]
Thanks!
